FROM ghcr.io/gohugoio/hugo:v0.152.1 AS builder

USER root

WORKDIR /src

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run speedtest:build && hugo --baseURL 'https://netzbremse.k1.muehlberger.dev/'

FROM nginx AS run

COPY --from=builder /src/public /usr/share/nginx/html 
