FROM  hugomods/hugo AS builder

WORKDIR /src

COPY package*.json .

RUN npm ci

COPY . . 

RUN hugo --baseURL 'https://netzbremse.k1.muehlberger.dev/'

FROM nginx AS run

COPY --from=builder /src/public /usr/share/nginx/html 
